import React from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
  const { language } = useLanguage();
  const content = {
    es: {
      title: 'Términos y Condiciones de Plixum',
      intro: `<b>Solutek Soluciones Integrales S.A.S.</b> (NIT: 900524319-8), en adelante "Plixum", te da la bienvenida. Antes de cualquier relación con nosotros, te invitamos a leer y aceptar nuestros Términos y Condiciones ("T&C"). Este documento regula el uso de nuestros servicios digitales y la página web <b>plixum.com</b>. Al acceder, registrarte, navegar, contratar nuestros servicios o disfrutar de nuestra plataforma, manifiestas tu adhesión libre y voluntaria a las condiciones aquí presentadas.`,
      sections: [
        { heading: '1. Ámbito de Aplicación', body: `<b>Plixum</b> ofrece sus servicios digitales, productos, plataformas, software, APIs y demás funcionalidades bajo el término "Servicios". Estos servicios son ofrecidos por <b>Solutek Soluciones Integrales S.A.S.</b>, sociedad legalmente constituida en Colombia, con sede principal en Colombia y NIT 900524319-8.` },
        { heading: '2. Aceptación y Responsabilidad del Usuario', body: `Al utilizar nuestros Servicios, asumes la responsabilidad de cumplir con estos T&C. Al aceptar este documento, autorizas a Plixum para el tratamiento de tus datos personales conforme a nuestra Política de Tratamiento de Datos Personales y Aviso de Privacidad.` },
        { heading: '3. Modificaciones', body: `Plixum podrá modificar estos T&C en cualquier momento, de manera unilateral y sin previo aviso. Si no estás de acuerdo con las modificaciones, deberás interrumpir el uso y comunicarte con nosotros.` },
        { heading: '4. Registro y Verificación', body: `Para acceder a los Servicios, deberás crear una cuenta de usuario y verificar tu identidad. Solicitaremos información personal (nombre, domicilio, documentos de identidad, información financiera) y realizaremos procesos de verificación KYC/KYT.` },
        { heading: '5. Declaraciones y Garantías', body: `La información que proporciones debe ser exacta y veraz. Te comprometes a mantenerla actualizada. Confirmas que tienes la capacidad legal y las autorizaciones necesarias. No debes usar medios automatizados para acceder a los Servicios sin consentimiento expreso.` },
        { heading: '6. Servicios y Operaciones', body: `Plixum facilita servicios de infraestructura financiera que incluyen: a) Recaudo de pagos globales mediante cuentas virtuales y rails bancarios regulados; b) Conversión y settlement entre monedas fiat y activos digitales a través de proveedores especializados; c) Payouts y transferencias a terceros; d) Automatización de flujos de tesorería. Plixum actúa como capa tecnológica de orquestación y no como banco, exchange, custodio financiero ni contraparte directa en las operaciones.` },
        { heading: '7. Naturaleza del Servicio', body: `Plixum opera como plataforma de infraestructura tecnológica financiera y orquestación de pagos. <b>Plixum no es una entidad vigilada por la Superintendencia Financiera de Colombia (SFC) ni por ninguna otra autoridad financiera.</b> Los fondos del Usuario son procesados por proveedores financieros regulados integrados a la plataforma, principalmente <b>Bridge.xyz</b> (entidad regulada en Estados Unidos), quien actúa como custodio del fiat y opera los rails bancarios internacionales (ACH, SEPA, Wire). El Usuario mantiene una relación directa con Bridge.xyz a través del proceso KYC/KYB. Plixum actúa exclusivamente como capa tecnológica de orquestación. Los contratos inteligentes (smart contracts) del Usuario en la red Solana son controlados por el propio Usuario, quien custodia sus propios activos digitales. Plixum no tiene acceso ni control sobre los fondos alojados en los smart contracts del Usuario.` },
        { heading: '8. Comisiones y Tarifas', body: `Las comisiones y tarifas de los Servicios se detallan en nuestros canales de comunicación y se actualizan periódicamente. Plixum cobra únicamente fees por servicios tecnológicos, orquestación, automatización e integración financiera. Los fondos del Usuario no son reconocidos como ingresos de Plixum.` },
        { heading: '9. Obligaciones Tributarias, Cambiarias y Regulatorias', body: `El Usuario es responsable de cumplir con la totalidad de sus obligaciones tributarias, contables y cambiarias derivadas del uso de los Servicios, incluyendo pero sin limitarse a: <br/><br/><b>a) Régimen Cambiario (Colombia):</b> Los residentes en Colombia que reciban divisas del exterior o realicen giros internacionales a través de los Servicios deben cumplir con el régimen cambiario colombiano establecido por el Banco de la República (Resolución Externa 1 de 2018 y sus modificaciones). Plixum no actúa como Intermediario del Mercado Cambiario (IMC). El Usuario es responsable de canalizar, declarar y reportar sus operaciones de cambio ante las entidades competentes cuando así lo exija la normativa aplicable.<br/><br/><b>b) Activos Virtuales y DIAN:</b> Conforme al Decreto 1089 de 2023 y la normativa vigente, los ingresos, ganancias y transacciones con activos virtuales pueden generar obligaciones tributarias ante la DIAN. El Usuario es responsable de declarar sus operaciones ante la autoridad tributaria colombiana.<br/><br/><b>c) Regulaciones Internacionales:</b> Usuarios ubicados en jurisdicciones distintas a Colombia deben cumplir con la normativa local aplicable a operaciones con activos digitales y pagos internacionales.<br/><br/>Plixum proporciona soporte documental (extractos, historial transaccional, reportes exportables) para facilitar la conciliación y auditoría del Usuario, pero no brinda asesoría contable, tributaria ni legal.` },
        { heading: '10. Condiciones de Uso', body: `Eres responsable de la privacidad y seguridad de tu usuario y contraseña. Todas las operaciones financieras son finales y no reembolsables. Plixum puede suspender o cancelar tu cuenta ante incumplimientos.` },
        { heading: '11. Cancelación de Cuentas', body: `Puedes solicitar la cancelación de tu cuenta en cualquier momento, siempre que no existan obligaciones pendientes ni saldos positivos. Plixum validará la solicitud y podrá retener activos hasta saldar obligaciones.` },
        { heading: '12. Propiedad Intelectual', body: `Todo el contenido de Plixum (software, textos, gráficos, logos, signos distintivos, animaciones, sonidos) es propiedad exclusiva de Solutek Soluciones Integrales S.A.S. Está prohibida la reproducción, ingeniería inversa o manipulación sin autorización.` },
        { heading: '13. Información Confidencial', body: `La información técnica, financiera, legal, comercial, know-how, clientes, socios y operaciones de Plixum es confidencial. Debes respetar la confidencialidad y evitar divulgaciones no autorizadas.` },
        { heading: '14. Riesgos y Limitación de Responsabilidad', body: `Reconoces que Plixum opera como infraestructura tecnológica y depende de proveedores financieros regulados de terceros. Plixum no se hace responsable por fallas, interrupciones o pérdidas originadas en dichos proveedores o en las redes blockchain subyacentes. El Usuario asume los riesgos operativos, de tipo de cambio, de liquidez y regulatorios propios de las operaciones financieras globales. Las transacciones confirmadas en blockchain no son reversibles.<br/><br/><b>Riesgos de Smart Contracts:</b> Los smart contracts desplegados en la red Solana están sujetos a riesgos tecnológicos inherentes, incluyendo vulnerabilidades de código, errores de protocolo y comportamientos inesperados. Plixum no garantiza la ausencia de errores en los contratos inteligentes ni se hace responsable por pérdidas derivadas de fallas técnicas en la red Solana o en los protocolos DeFi integrados (Jupiter Exchange, entre otros).<br/><br/><b>Custodia del Usuario:</b> El Usuario es el único responsable de la seguridad de sus claves privadas y del acceso a su wallet. Si el Usuario pierde el acceso a su wallet o claves privadas, Plixum no puede recuperar los fondos. No existe mecanismo de recuperación centralizado para activos en smart contracts bajo custodia del Usuario.` },
        { heading: '15. Cumplimiento y SAGRILAFT', body: `Plixum opera bajo altos estándares de cumplimiento normativo, ajustándose a la legislación colombiana y lineamientos internacionales. Implementamos el Sistema de Administración y Gestión de Lavado de Activos, Financiación del Terrorismo y Financiamiento de la Proliferación de Armas de Destrucción Masiva (SAGRILAFT).` },
        { heading: '16. Legislación Aplicable', body: `Estos T&C se rigen por las leyes de la República de Colombia. Cualquier controversia será resuelta por los tribunales competentes de Colombia.` },
        { heading: '17. Solución de Conflictos', body: `Las partes buscarán una solución amistosa ante cualquier conflicto. Si no se logra, la controversia se someterá a la jurisdicción de los jueces Barranquilla.` },
        { heading: '18. Vigencia', body: `Estos T&C están vigentes desde el 01 de enero de 2024 y aplican a todos los Servicios realizados desde su publicación. Plixum podrá ajustarlos periódicamente.` },
        { heading: '19. Aviso Regulatorio', body: `<b>Plixum (Solutek Soluciones Integrales S.A.S.) no es una entidad vigilada por la Superintendencia Financiera de Colombia (SFC), el Banco de la República, ni por ninguna otra autoridad financiera o de valores.</b> Los servicios de infraestructura tecnológica ofrecidos por Plixum no constituyen captación masiva de dinero, intermediación financiera, custodia de valores, ni transmisión de dinero en los términos definidos por la legislación financiera colombiana. Las operaciones fiat internacionales son procesadas por <b>Bridge.xyz</b>, entidad regulada en los Estados Unidos. El Usuario declara conocer y aceptar estas condiciones, así como su responsabilidad de cumplir con las obligaciones cambiarias y tributarias que le sean aplicables en su jurisdicción.` },
        { heading: '20. Ausencia de Asesoría', body: `Plixum no presta servicios de asesoría financiera, tributaria, contable, legal ni de inversión. Ninguna información, comunicación, funcionalidad de la plataforma, material de marketing o interacción con el equipo de Plixum debe interpretarse como asesoría profesional de ningún tipo. El Usuario reconoce que cualquier decisión financiera, operativa o de cumplimiento que tome en el marco del uso de los Servicios es de su exclusiva responsabilidad. En caso de requerir orientación especializada, el Usuario deberá consultar a un profesional independiente calificado en la materia correspondiente.` },
        { heading: '21. Contacto', body: `Para consultas, contáctanos en <b>info@plixum.com</b>.` },
      ],
      updated: 'Última actualización: Julio 2026',
    },
    en: {
      title: 'Plixum Terms and Conditions',
      intro: `<b>Solutek Soluciones Integrales S.A.S.</b> (NIT: 900524319-8), hereinafter "Plixum", welcomes you. Before any relationship with us, please read and accept our Terms and Conditions ("T&C"). This document governs the use of our digital services and the website <b>plixum.com</b>. By accessing, registering, browsing, contracting our services, or using our platform, you freely and voluntarily adhere to the conditions presented here.`,
      sections: [
        { heading: '1. Scope of Application', body: `<b>Plixum</b> offers its digital services, products, platforms, software, APIs, and other functionalities under the term "Services". These services are provided by <b>Solutek Soluciones Integrales S.A.S.</b>, a legally established company in Colombia, headquartered in Colombia, NIT 900524319-8.` },
        { heading: '2. Acceptance and User Responsibility', body: `By using our Services, you assume the responsibility to comply with these T&C. By accepting this document, you authorize Plixum to process your personal data in accordance with our Personal Data Processing Policy and Privacy Notice.` },
        { heading: '3. Modifications', body: `Plixum may modify these T&C at any time, unilaterally and without prior notice. If you disagree with the modifications, you must stop using the platform and contact us.` },
        { heading: '4. Registration and Verification', body: `To access the Services, you must create a user account and verify your identity. We will request personal information (name, address, identity documents, financial information) and conduct KYC/KYT verification processes.` },
        { heading: '5. Declarations and Warranties', body: `The information you provide must be accurate and truthful. You commit to keeping it updated. You confirm that you have the legal capacity and necessary authorizations. You must not use automated means to access the Services without express consent.` },
        { heading: '6. Services and Operations', body: `Plixum facilitates financial infrastructure services including: a) Global payment collection via regulated virtual accounts and banking rails; b) Conversion and settlement between fiat currencies and digital assets through specialized providers; c) Cross-border payouts and third-party transfers; d) Treasury workflow automation. Plixum acts as a technology orchestration layer and not as a bank, exchange, financial custodian, or direct counterpart in transactions.` },
        { heading: '7. Nature of Service', body: `Plixum operates as a technology financial infrastructure and payment orchestration platform. <b>Plixum is not an entity supervised by the Superintendencia Financiera de Colombia (SFC) or any other financial authority.</b> User funds are processed by regulated financial providers integrated into the platform, primarily <b>Bridge.xyz</b> (a regulated entity in the United States), which acts as the fiat custodian and operates international banking rails (ACH, SEPA, Wire). The User maintains a direct relationship with Bridge.xyz through the KYC/KYB process. Plixum acts exclusively as a technology orchestration layer. The User’s smart contracts on the Solana network are controlled by the User themselves, who self-custodies their own digital assets. Plixum has no access to or control over funds held in the User’s smart contracts.` },
        { heading: '8. Fees and Charges', body: `Service fees and charges are detailed in our communication channels and updated periodically. Plixum charges fees exclusively for technology services, orchestration, automation, and financial integration. User funds are not recognized as Plixum income.` },
        { heading: '9. Tax, Exchange, and Regulatory Obligations', body: `The User is responsible for complying with all tax, accounting, and foreign exchange obligations derived from use of the Services, including but not limited to:<br/><br/><b>a) Foreign Exchange Regime (Colombia):</b> Colombian residents who receive foreign currency from abroad or make international transfers through the Services must comply with the Colombian foreign exchange regime established by the Banco de la República (External Resolution 1 of 2018 and its amendments). Plixum does not act as a Certified Foreign Exchange Intermediary (IMC). The User is responsible for channeling, declaring, and reporting their exchange operations to the competent authorities where required by applicable regulations.<br/><br/><b>b) Virtual Assets and DIAN:</b> Pursuant to Decree 1089 of 2023 and applicable regulations, income, gains, and transactions involving virtual assets may generate tax obligations before the DIAN. The User is responsible for declaring their operations to the Colombian tax authority.<br/><br/><b>c) International Regulations:</b> Users located in jurisdictions other than Colombia must comply with locally applicable regulations regarding digital asset operations and international payments.<br/><br/>Plixum provides documentary support (statements, transaction history, exportable reports) to facilitate User reconciliation and auditing, but does not provide accounting, tax, or legal advice.` },
        { heading: '10. Terms of Use', body: `You are responsible for the privacy and security of your username and password. All financial operations are final and non-refundable. Plixum may suspend or cancel your account in case of breaches.` },
        { heading: '11. Account Cancellation', body: `You may request account cancellation at any time, provided there are no pending obligations or positive balances. Plixum will validate the request and may retain assets until obligations are settled.` },
        { heading: '12. Intellectual Property', body: `All Plixum content (software, texts, graphics, logos, trademarks, animations, sounds) is the exclusive property of Solutek Soluciones Integrales S.A.S. Reproduction, reverse engineering, or manipulation without authorization is prohibited.` },
        { heading: '13. Confidential Information', body: `Technical, financial, legal, commercial, know-how, client, partner, and operational information of Plixum is confidential. You must respect confidentiality and avoid unauthorized disclosures.` },
        { heading: '14. Risks and Limitation of Liability', body: `You acknowledge that Plixum operates as a technology infrastructure layer and depends on regulated third-party financial providers. Plixum is not responsible for failures, interruptions, or losses originating from such providers or the underlying blockchain networks. The User assumes operational, foreign exchange, liquidity, and regulatory risks inherent to global financial operations. Transactions confirmed on blockchain are not reversible.<br/><br/><b>Smart Contract Risks:</b> Smart contracts deployed on the Solana network are subject to inherent technological risks, including code vulnerabilities, protocol errors, and unexpected behavior. Plixum does not guarantee the absence of errors in smart contracts and is not liable for losses resulting from technical failures in the Solana network or integrated DeFi protocols (Jupiter Exchange, among others).<br/><br/><b>User Self-Custody:</b> The User is solely responsible for the security of their private keys and wallet access. If the User loses access to their wallet or private keys, Plixum cannot recover the funds. There is no centralized recovery mechanism for assets in User-controlled smart contracts.` },
        { heading: '15. Compliance and SAGRILAFT', body: `Plixum operates under high standards of regulatory compliance, adhering to Colombian law and international guidelines. We implement the System for the Administration and Management of Money Laundering, Terrorism Financing, and Financing of the Proliferation of Weapons of Mass Destruction (SAGRILAFT).` },
        { heading: '16. Applicable Law', body: `These T&C are governed by the laws of the Republic of Colombia. Any dispute will be resolved by the competent courts of Colombia.` },
        { heading: '17. Dispute Resolution', body: `The parties will seek an amicable solution to any conflict. If not achieved, the dispute will be submitted to the jurisdiction of the courts of Colombia.` },
        { heading: '18. Validity', body: `These T&C are effective as of January 1, 2024 and apply to all Services performed since their publication. Plixum may adjust them periodically.` },
        { heading: '19. Regulatory Notice', body: `<b>Plixum (Solutek Soluciones Integrales S.A.S.) is not an entity supervised by the Superintendencia Financiera de Colombia (SFC), the Banco de la República, or any other financial or securities authority.</b> The technology infrastructure services offered by Plixum do not constitute mass deposit-taking, financial intermediation, securities custody, or money transmission as defined by Colombian financial legislation. International fiat operations are processed by <b>Bridge.xyz</b>, a regulated entity in the United States. The User acknowledges and accepts these conditions, as well as their responsibility to comply with any foreign exchange and tax obligations applicable in their jurisdiction.` },
        { heading: '20. Absence of Advisory', body: `Plixum does not provide financial, tax, accounting, legal, or investment advisory services. No information, communication, platform functionality, marketing material, or interaction with the Plixum team should be interpreted as professional advice of any kind. The User acknowledges that any financial, operational, or compliance decision made in the context of using the Services is their sole responsibility. If specialized guidance is required, the User should consult an independent qualified professional in the relevant field.` },
        { heading: '21. Contact', body: `For inquiries, contact us at <b>info@plixum.com</b>.` },
      ],
      updated: 'Last updated: July 2026',
    },
  };
  const lang = content[language];
    return (
      <div className="min-h-screen flex flex-col bg-background">
        <Header />
        <main className="flex-1">
          <div className="container mx-auto px-4 py-12 max-w-3xl">
            <h1 className="text-4xl font-bold mb-8 text-black">{lang.title}</h1>
            <p className="mb-4 text-lg text-foreground" dangerouslySetInnerHTML={{ __html: lang.intro }} />
            {lang.sections.map((section, idx) => (
              <React.Fragment key={idx}>
                <h2 className="text-2xl font-bold mt-8 mb-4 text-black">{section.heading}</h2>
                <p className="mb-4 text-foreground" dangerouslySetInnerHTML={{ __html: section.body }} />
              </React.Fragment>
            ))}
            <p className="mt-8 text-muted-foreground text-sm">{lang.updated}</p>
          </div>
        </main>
      <Footer />
    </div>
  );
};

export default TermsOfService;
